JAV-288: 优化本地IDE运行配置
ServiceComb/ServiceComb-Company-WorkShop pull request #18
Opened 2017-08-10 13:10 UTC by TankTian

https://servicecomb.atlassian.net/browse/JAV-288

修改点：
1、本地微服务描述文件，服务中心地址默认改为127.0.0.1方便连接本地调试直接启动服务中心。（不影响docker-compose域名连接服务中心，docker-compose.yml通过环境变量传入即可）
2、各微服务默认端口需要不同，以免非容器环境单机会冲突。
3、manager服务对外端口默认开启，不需要额外参数传入，简化运行

2017-08-13 03:09 UTC, WillemJiang commented on beekeeper/src/main/resources/microservice.yaml
> +      address: http://127.0.0.1:30100
通过dev profile来设置

2017-08-14 00:57 UTC, seanyinx commented
this is a reason to use hostname instead of loopback ip. using automated tests to ensure all changes are good instead of changing the address and ports, and testing manually.

2017-08-14 00:59 UTC, seanyinx requested changes

2017-08-14 00:59 UTC, seanyinx commented on beekeeper/src/main/resources/microservice.yaml
> -      address: http://sc.servicecomb.io:30100
always think about automated tests instead of making changes to suit manually testing locally

2017-08-14 13:16 UTC, TankTian commented on beekeeper/src/main/resources/microservice.yaml
> -      address: http://sc.servicecomb.io:30100
此处域名移动到docker-compose.yml中设置，一样不影响自动化测试。 同时这样修改是为了简化本地直接启动系统用，了解本地服务中心进行开发调试。增加了场景而且不影响自动化测试。个人建议还是要修改。

2017-08-14 13:17 UTC, TankTian commented on beekeeper/src/main/resources/microservice.yaml
> +      address: http://127.0.0.1:30100
默认应该支持的行为应该是本地运行的能力。dev profile是用在上云或者自动化测试的时候，动态去覆盖该配置项。

2018-07-30 03:54 UTC, WillemJiang commented
Just close this issue as it's very old.

2018-07-30 03:54 UTC, closed without merging